#!/bin/bash
echo "Install Windows 10"
echo "This step by step has been created from information provided by the OP, @Marcel Alexandru."
echo "Backup the Target drive."

echo "Create a 6GB NTFS partition on the hard drive and extract the Windows ISO to it."
# to create the partitions programatically (rather than manually)
# we're going to simulate the manual input to fdisk
# The sed script strips off all the comments so that we can 
# document what we're doing in-line with the actual commands
# Note that a blank line (commented as "defualt" will send a empty
# line terminated with a newline to take the fdisk default.
sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | fdisk ${TGTDEV}
  o # clear the in memory partition table
  n # new partition
  p # primary partition
  1 # partition number 1
    # default - start at beginning of disk 
  +100M # 100 MB boot parttion
  n # new partition
  p # primary partition
  2 # partion number 2
    # default, start immediately after preceding partition
    # default, extend partition to end of disk
  a # make a partition bootable
  1 # bootable partition is partition 1 -- /dev/sda1
  p # print the in-memory partition table
  w # write the partition table
  q # and we're done
  
echo "Create a 20GB, or larger, NTFS partition on the hard drive for the Windows Installation."
#echo "Open Disks, (Gnome-Disks), and note Device, (/dev/sdx), and UUID of the Windows ISO extract partition."
#echo "For msdos partition table, copy the menuentry given in this question to /etc/grub.d/40-custom/*"
#echo "Add ntldr /bootmgr as a line below chainloader +1"
#echo "Edit menuentry, changing sda4 to sdax, msdos4 to msdosx (4 places), and 592C85254E2CD0B7 to UUID, (3 places), to suit step 4 above."
#echo "Run sudo update grub confirm that ntldr /bootmgr appears in grub.cfg."
#echo "Boot the computer into the newly created menuentry and install Windows into it's new partition."
#echo "Reinstall Ubuntu if desired, the GRUB bootloader will have been replaced with the Windows bootloader."
